pipeline {
    agent any
    stages {
        stage('Lint HTML') {
            steps {
                sh 'tidy -q -e *.html'
            }
        }
        stage('Build Docker image') {
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
                    sh '''
                        docker build -t pyrrhus/udacity-capstone .
                        '''
            }
        }
    }
    stage('Push image to DockerHub') {
        steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
                    sh '''
                        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                        docker push pyrrhus/udacity-capstone
                    '''
                }
            }
        }
    stage('Set current kubectl context') {
            steps {
                withAWS(region:'us-east-1', credentials:'jenkins_creds') {
                    sh '''
                        kubectl config use-context arn:aws:eks:us-east-2:142977788479:cluster/finalCluster
                    '''
                }
            }
        }
    }
}